#!/bin/tcsh

foreach file (/home/tptp/TDTP/MPTPTP2078/Chainy/Problems/MPT1[5-9]*.p)
    set problem = `basename $file`
    run_glgg "$file" "MPTPTPChainy2078_GEHD/$problem" |& grep -v "Warning"
    echo $problem
end
